### ISSUE TITLE
fix deployment of git repos when they already exist

### ISSUE THREAD

**Issue by alex-bue** [alex-bue/dotfiles#5]
Ansible exits early when the repository already exists locally when running tasks like this one:
```
- name: "clone powerlevel10k"
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ ansible_user_dir }}/.config/zsh/zsh_plugins/powerlevel10k"
    version: HEAD
    clone: true
    update: true
```

This is troublesome if I want to rerun the script at any point in the future.

---

Log:

```
TASK [zsh : clone powerlevel10k] ***********************************************************************************
Tuesday 05 December 2023  20:25:06 +0100 (0:00:00.353)       0:01:28.431 ******
fatal: [127.0.0.1]: FAILED! => changed=false
  cmd: /usr/local/bin/git clone --origin origin https://github.com/romkatv/powerlevel10k.git /Users/ab/.config/zsh/zsh_plugins/powerlevel10k
  msg: 'fatal: destination path ''/Users/ab/.config/zsh/zsh_plugins/powerlevel10k'' already exists and is not an empty directory.'
  rc: 128
  stderr: |-
    fatal: destination path '/Users/ab/.config/zsh/zsh_plugins/powerlevel10k' already exists and is not an empty directory.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
